services:
  reth:
    restart: always
    image: "ghcr.io/paradigmxyz/reth:v1.3.12"
    volumes:
      - type: bind
        source: ./reth_chaindata
        target: /chaindata

    command: node --dev --datadir /rethdata --http --http.corsdomain "*" --http.addr 0.0.0.0 --http.port 8545 --dev.block-time 6s --chain /chaindata/reth_config 
    environment:
      - RUST_LOG=info
    ports:
      - 127.0.0.1:8545:8545
  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword
  zksync:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:${INSTANCE_TYPE:-latest2.0}
    healthcheck:
      test: curl --fail http://localhost:3071/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 200
      start_period: 30s
    depends_on:
      - reth
      - postgres
    ports:
      - 127.0.0.1:3050:3050 # JSON RPC HTTP port
      - 127.0.0.1:3051:3051 # JSON RPC WS port
    environment:
      - DATABASE_PROVER_URL=postgres://postgres:notsecurepassword@postgres/prover_local
      - DATABASE_URL=postgres://postgres:notsecurepassword@postgres/zksync_local
      - ETH_CLIENT_WEB3_URL=http://reth:8545 
      - ZKSYNC_SKIP_PROVER=1

volumes:
  reth:
